### ISSUE TITLE
Question on the support of QSS

### ISSUE THREAD

**Issue by jcelerier** [KDAB/qsslint#1]
Regarding : https://github.com/KDAB/qsslint/blob/3dbe4d55699e26daa898018909ef2ef567130a62/main.cpp#L89

How do you propose that: 
- designers with almost zero experience in code at all (e.g., QML is too hard) change the UI ? 
- live edition and reloading of styles be handled ? that's currently one of the features of my software that users are fairly happy to use : they can just edit the qss in a small dialog and see their changes directly & save these as theme files. How is this use-case handled with QStyle inheritance, short of shipping LLVM with my software and live-recompiling the QStyle subclass ?

**Comment by iamsergio** [comment]
I don't think those are issues of the tool (qsslint), but rather something that should be solved at the qt-project level, by for example not removing stylesheet support from Qt 6, but it's not my call.

FWIW, after hearing it could be removed I started QTBUG-68671 and proposed it be factored out of qtbase and moved to qtstyleplugins repo instead of removal.
